### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by cowlicker12** [ProgrammingIncluded/PyYugi#3]
I installed the requirements and then tried to run main.py, but it gives the error in the title pointing to yugidb.py line 13. Is something missing from the requirements.txt that would handle this?

**Comment by ProgrammingIncluded** [comment]
Hi @cowlicker12 yes, the requirements.txt may not have been updated accurately, you would want to install `requests`. Try running `pip install requests`. https://pypi.org/project/requests/
